extensions.autofillForms@blueimp.net.description=Автоматичне заповнення вебформ
extensions.autofillForms@blueimp.net.shortcut=alt+J
extensions.autofillForms@blueimp.net.shortcutSubmit=
extensions.autofillForms@blueimp.net.shortcutAllTabs=
extensions.autofillForms@blueimp.net.shortcutFromProfileSelection=
extensions.autofillForms@blueimp.net.shortcutProfile=control+alt+J
extensions.autofillForms@blueimp.net.shortcutSettings=control+alt+shift+J
extensions.autofillForms@blueimp.net.shortcutDisplayFormDetails=
extensions.autofillForms@blueimp.net.fieldRules=Імʼя користувача		(?:(?:user)|(?:login))(?!\\w*pass)	(?:)	true	true\nЕлектронна пошта		mail	(?:)	true	true\nЗвертання		(?:prefix\\w*name)|(?:name\\w*prefix)|(?:title)	(?:)	true	true\nІмʼя		(?:first\\w*name)|(?:name\\w*first)	(?:)	true	true\nПо батькові		(?:middle\\w*name)|(?:name\\w*middle)	(?:)	true	true\nПрізвище		(?:last\\w*name)|(?:name\\w*last)	(?:)	true	true\nСуфікс імені		(?:suffix\\w*name)|(?:name\\w*suffix)	(?:)	true	true\nПовне імʼя		name	(?:)	true	true\nВулиця (рядок 1)		(?:(?:street)|(?:addr))\\w*1	(?:)	true	true\nВулиця (рядок 2)		(?:(?:street)|(?:addr))\\w*2	(?:)	true	true\nВулиця (рядок 3)		(?:(?:street)|(?:addr))\\w*3	(?:)	true	true\nВулиця (повністю)		(?:street)|(?:addr)	(?:)	true	true\nМісто		city	(?:)	true	true\nОбласть / регіон		(?:state)|(?:prov)|(?:region)	(?:)	true	true\nПоштовий індекс		(?:zip)|(?:post\\w*code)	(?:)	true	true\nКод країни		country\\w*code	(?:)	true	true\nКраїна		country	(?:)	true	true\nМова		lang	(?:)	true	true\nДень народження		(?:bday)|(?:birth\\w?day)|(?:dob\\w?day)|(?:birth\\w*1)	(?:)	true	true\nМісяць народження		(?:bmon)|(?:birth\\w?mon)|(?:dob\\w?mon)|(?:birth\\w*2)	(?:)	true	true\nРік народження		(?:byear)|(?:birth\\w?year)|(?:dob\\w?year)|(?:birth\\w*3)	(?:)	true	true\nКомпанія		company	(?:)	true	true\nПосада		(?:occupation)|(?:job)	(?:)	true	true\nТелефон		(?:phone)|(?:tel)	(?:)	true	true\nДомашня сторінка		(?:web)|(?:homepage)|(?:www)|(?:url)	(?:)	true	true
extensions.autofillForms@blueimp.net.profileLabels=За замовчуванням
extensions.autofillForms@blueimp.net.dynamicTags=<дата_і_час>	<агент_користувача>	<код_мови>	<роздільна_здатність>	<буфер_обміну>
extensions.autofillForms@blueimp.net.dynamicTagCodes=new Date().toLocaleString()	navigator.userAgent	navigator.language	screen.width+'x'+screen.height	this.getClipboardText()
extensions.autofillForms@blueimp.net.regExpPasswordLabel=(?:пароль)
tooltip=Заповнити форми
tooltipSubmit=Заповнити та надіслати форми
tooltipAllTabs=Заповнити форми на всіх вкладках
tooltipFromProfileSelection=Заповнити форми з вибраного профілю
tooltipProfile=Перемикач профілів
tooltipSettings=Налаштування
tooltipDisplayFormDetails=Показати деталі форми
currentProfileLabel=Поточний профіль:
profileSelectionWindowTitle=Змінити профіль
profileSelectionFormFillTitle=Заповнення форм
profileSelectionPrompt=Виберіть профіль:
contextMenuMore=Більше…
invalidRegExpTitle=Неприпустимий регулярний вираз
invalidRegExpText=Введений регулярний вираз є недійсним:
containsRuleType=містить
beginsWithRuleType=починається з
endsWithRuleType=закінчується на
equalsRuleType=дорівнює
alternativesSelectionWindowTitle=Вибір альтернативи
alternativesSelectionPrompt=Виберіть альтернативу:
importProfile=Імпортувати профіль
exportProfile=Експортувати профіль
importDynamicTags=Імпортувати динамічні теги
exportDynamicTags=Експортувати динамічні теги
removeProfileTitle=Видалити профіль
removeProfileText=Справді видалити поточний профіль?
removeFieldRulesTitle=Видалити правила полів
removeFieldRulesText=Справді видалити вибрані правила полів?
sortFieldRulesTitle=Сортувати правила полів
sortFieldRulesText=Справді встановити новий порядок правил полів?
removeRuleConditionTitle=Видалити умову правила
removeRuleConditionText=Справді видалити вибрану умову правила?
removeDynamicTagTitle=Видалити динамічний тег
removeDynamicTagText=Справді видалити вибраний динамічний тег?
resetAllProfilesTitle=Скинути всі профілі
resetAllProfilesText=Справді скинути всі профілі?
selectConfigDirectory=Вибрати каталог конфігурації
newConfigDirectoryNotEmptyTitle=Каталог не порожній
newConfigDirectoryNotEmptyText=Новий каталог конфігурації не порожній. Бажаєте перезаписати наявні файли конфігурації?
importFromConfigDirectoryTitle=Імпорт із каталогу конфігурації
importFromConfigDirectoryText=Бажаєте перезаписати профілі даними з каталогу конфігурації?
command=Команда
mousebutton=Кнопка миші
mousebutton0=Ліва кнопка миші
mousebutton1=Середня кнопка миші
mousebutton2=Права кнопка миші
keyboardShortcut=Комбінація клавіш
alt=Alt
control=Ctrl
meta=Cmd
shift=Shift
VK_CANCEL=Скасувати
VK_HELP=Довідка
VK_BACK=Пробіл
VK_TAB=Tab
VK_CLEAR=Очистити
VK_RETURN=Return
VK_ENTER=Enter
VK_PAUSE=Пауза
VK_CAPS_LOCK=Caps Lock
VK_ESCAPE=Esc
VK_SPACE=Пробіл
VK_PAGE_UP=Page Up
VK_PAGE_DOWN=Page Down
VK_END=End
VK_HOME=Home
VK_LEFT=Вліво
VK_UP=Вгору
VK_RIGHT=Вправо
VK_DOWN=Вниз
VK_PRINTSCREEN=Print Screen
VK_INSERT=Insert
VK_DELETE=Delete
VK_NUM_LOCK=Num Lock
VK_SCROLL_LOCK=Scroll Lock
